# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: John Doe
description: "Hi I'm John, and I'm an aspiring Data Scientist.  I'm currently building up my portfolio which focuses on interesting and impactful projects I've recently undertaken. You can visit my Github and LinkedIn pages, and download my resume by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/#" # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: true


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

